# Generated by Django 4.2.26 on 2025-11-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0002_add_user_to_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="award",
            options={"ordering": ["-year"]},
        ),
        migrations.AlterModelOptions(
            name="education",
            options={"ordering": ["-grad_year"]},
        ),
        migrations.AlterModelOptions(
            name="professionalexperience",
            options={"ordering": ["-start_year"]},
        ),
        migrations.AlterModelOptions(
            name="publication",
            options={"ordering": ["-id"]},
        ),
        migrations.AddField(
            model_name="publication",
            name="authors",
            field=models.TextField(
                blank=True, help_text="Comma-separated list of authors"
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="issue",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="publication",
            name="journal",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="publication",
            name="pages",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="publication",
            name="title",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="publication",
            name="volume",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="publication",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="publication",
            index=models.Index(fields=["title"], name="cv_publicat_title_9b3318_idx"),
        ),
        migrations.AddIndex(
            model_name="publication",
            index=models.Index(fields=["doi"], name="cv_publicat_doi_d20c7b_idx"),
        ),
    ]
